-- MySQL Script generated by MySQL Workbench
-- Mon May 12 09:46:32 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bank
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema `bank`
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bank` DEFAULT CHARACTER SET utf8 ;
USE `bank` ;

-- -----------------------------------------------------
-- Table `bank_system`.`users` 使用者資料表
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`users` ;

CREATE TABLE IF NOT EXISTS `bank`.`users` (
  `user_id` VARCHAR(15) NOT NULL,          -- 使用者身分證字號
  `user_name` VARCHAR(45) NOT NULL,        -- 使用者名稱
  `password` VARCHAR(100) NOT NULL,        -- 密碼
  PRIMARY KEY (`user_id`))                 -- 主鍵：身分證字號
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bank_system`.`accounts` 帳戶資料表
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`accounts` ;

CREATE TABLE IF NOT EXISTS `bank`.`accounts` (
  `account_id` INT NOT NULL AUTO_INCREMENT,                    	-- 帳戶id（自動生成）
  `account_num` VARCHAR(15) NOT NULL,                           -- 帳戶帳號
  `currency_code` VARCHAR(3) NOT NULL DEFAULT 'TWD',			-- 帳戶幣別
  `init_balance` DECIMAL(15,2) NULL DEFAULT 0.00,               -- 初始餘額
  `user_id` VARCHAR(15) NOT NULL,                               -- 帳戶所屬的使用者id
  `create_at` DATETIME NOT NULL,                                -- 開戶時間
  PRIMARY KEY (`account_id`),									-- 主鍵：帳戶id
  UNIQUE INDEX `account_num_UNIQUE` (`account_num` ASC) VISIBLE,-- 帳戶帳號必為唯一
  UNIQUE INDEX `account_id_UNIQUE` (`account_id` ASC) VISIBLE,
  INDEX `user_accounts_fk_idx` (`user_id` ASC) VISIBLE,         -- 外鍵：使用者的帳戶（一對多）
  CONSTRAINT `user_accounts_fk`
    FOREIGN KEY (`user_id`)
    REFERENCES `bank`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `bank.`account_balance` 帳戶的各個幣別餘額
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`account_balance` ;

CREATE TABLE IF NOT EXISTS `bank`.`account_balance` (
  `account_id` INT NOT NULL,									-- 所屬的帳戶編號
  `balance` DECIMAL(15,2) NULL DEFAULT 0.00,					-- 餘額
  `currency_code` VARCHAR(3) NOT NULL DEFAULT 'TWD',			-- 幣別
  INDEX `account_balances_fk_idx` (`account_id` ASC) VISIBLE,	-- 建立外鍵
  PRIMARY KEY (`account_id`, `currency_code`),					-- 主鍵：帳戶編號+幣別
  CONSTRAINT `account_balances_fk`								-- 外鍵：所屬帳號（一對多）
    FOREIGN KEY (`account_id`)
    REFERENCES `bank`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bank`.`transaction_record`交易紀錄資料表
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bank`.`transaction_record` ;

CREATE TABLE IF NOT EXISTS `bank`.`transaction_record` (
  `transaction_record_id` INT NOT NULL AUTO_INCREMENT,					-- 交易紀錄編號
  `account_id` INT NOT NULL,											-- 所屬帳戶
  `create_at` DATETIME NULL,											-- 建立時間
  `transaction_type` VARCHAR(45) NOT NULL,								-- 交易類型（例：提款、買入外幣）
  `tx_amt` DECIMAL(15,2) NOT NULL DEFAULT 0.00,							-- 交易金額 
  `tempbalance` DECIMAL(15,2) NOT NULL DEFAULT 0.00,					-- 當筆交易餘額
  `currency_code` VARCHAR(3) NOT NULL DEFAULT 'TWD',					-- 交易幣別
  `record` VARCHAR(500) DEFAULT '',										-- 紀錄交易字串
  PRIMARY KEY (`transaction_record_id`),								-- 主鍵：交易紀錄編號、所屬帳戶編號
  INDEX `account_transaction_record_fk_idx` (`account_id` ASC) VISIBLE, 
  INDEX `transaction_currency_idx` (`currency_code` ASC) VISIBLE,
  CONSTRAINT `account_transaction_record_fk`							-- 外鍵：所屬帳戶（一對多）
    FOREIGN KEY (`account_id`)
    REFERENCES `bank`.`accounts` (`account_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;



SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;